<?php

return [
    [
        'name' => 'ini',
        'title' => '客户端配置',
        'type' => 'array',
        'value' => [
            'name' => 'Estar元宇宙',
            'logo' => '/uploads/20220507/534ea974c7a151255fb5f5259668b81b.jpg',
            'versions' => '1.0.0',
            'tel_phone' => '13085057695',
            'working_hours' => '24小时',
            'shop_qun' => '125123123',
            'company_mail' => '123456@qq.com',
            'service_mail' => '123123123@qq.com',
            'box_poster' => '/uploads/20220324/9ebacc7048fc9502da3b50675bf06140.png',
            'poster' => '2321321',
            'poster_h5' => '/uploads/20220321/16b277a4103a9bee4e699cea33ff5487.jpg',
            'poster_text' => '分享文案',
            'REDIS_HOST' => '127.0.0.1',
            'REDIS_PORT' => '6379',
            'REDIS_PASSWORD' => '',
            'REDIS_DB' => '2',
            'balance_pay' => '0',
            'wechat_pay' => '1',
            'alipay_pay' => '1',
            'make_give' => '0',
            'identify' => '1',
            'identify_appcode' => '35fc6685b5ef4a2dbad8a5e53ca07d02',
            'warning' => '购买须知'."\r\n"
                .'312321321'."\r\n"
                .'321321321',
            'pay_limit_time' => '0',
            'remind' => '123123123',
        ],
        'rule' => '',
        'msg' => '',
        'tip' => '客户端参数配置',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'config',
        'title' => '文案配置',
        'type' => 'array',
        'value' => [
            'privacy_protection' => '7',
            'user_agreement' => '6',
            'punish_protection' => '8,9',
            'category' => '{"series":"\\u85cf\\u54c1\\u7cfb\\u5217"}',
            'make_friend' => '12',
        ],
        'rule' => '',
        'msg' => '',
        'tip' => '文案配置',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'marketing',
        'title' => '营销配置',
        'type' => 'array',
        'value' => [
            'air_drop' => '10',
            'box' => '11',
            'compound' => '11',
            'badge_no' => '0',
            'give_status' => '0',
            'badge_rule' => '1',
            'base_badge_id' => '2',
            'badge_up_number' => '2',
            'up_badge_id' => '1',
            'up_badge_text' => '10',
        ],
        'rule' => '',
        'msg' => '',
        'tip' => '营销参数配置',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'withdraw',
        'title' => '提现',
        'type' => 'array',
        'value' => [
            'servicefee' => '0.6',
            'rule' => '323213',
            'state' => '1',
            'minmoney' => '0',
            'monthlimit' => '0',
        ],
        'rule' => '',
        'msg' => '',
        'tip' => '提现参数配置',
        'ok' => '',
        'extend' => '',
    ],
];
